USE master
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'SNInterDev') BEGIN
   CREATE DATABASE [SNInterDev];
END
GO

USE SNInterDev;
GO

CREATE SCHEMA oys;
GO

USE SNInterDev;
CREATE TABLE oys.Program (
	AutoId BIGINT IDENTITY(1,1) NOT NULL,
	DBEntryDateTime DATETIME DEFAULT GETDATE(),
	ProgramGUID UNIQUEIDENTIFIER NOT NULL,
	ProgramName VARCHAR(50),
	LayoutNumber INT,
	MachineName VARCHAR(50),
	CuttingTime FLOAT,
	TaskName VARCHAR(50),
	NestType VARCHAR(64),	-- 'Slab', 'Standard' or 'Split'
	WSName NVARCHAR(300)
);
GO
ALTER TABLE oys.Program
ADD CONSTRAINT PK_Program PRIMARY KEY NONCLUSTERED (ProgramGUID);
CREATE UNIQUE CLUSTERED INDEX IX_AutoId ON oys.Program(AutoId);
GO

USE SNInterDev;
CREATE TABLE oys.ParentPlate
(
	AutoId BIGINT IDENTITY(1,1) NOT NULL,
	DBEntryDateTime DATETIME DEFAULT GETDATE(),
	ProgramGUID UNIQUEIDENTIFIER NOT NULL,
	PlateName VARCHAR(50),
	Material VARCHAR(50),
	Thickness FLOAT,
	Area FLOAT
);
GO
ALTER TABLE oys.ParentPlate
ADD CONSTRAINT PK_ParentPlate PRIMARY KEY NONCLUSTERED (ProgramGUID);
ALTER TABLE oys.ParentPlate
ADD CONSTRAINT FK_ParentPlate_Program FOREIGN KEY (ProgramGUID)
  REFERENCES oys.Program(ProgramGUID) ON DELETE CASCADE;
CREATE UNIQUE CLUSTERED INDEX IX_AutoId ON oys.ParentPlate(AutoId);
GO

USE SNInterDev;
CREATE TABLE oys.ParentPart(
	AutoId BIGINT IDENTITY(1,1) NOT NULL,
	DBEntryDateTime DATETIME DEFAULT GETDATE(),
	ProgramGUID UNIQUEIDENTIFIER NOT NULL,
	ParentPartGUID UNIQUEIDENTIFIER NOT NULL,
	SNPartName VARCHAR(100),
	QtyProgram INT,
	TrueArea FLOAT,
	NestedArea FLOAT
);
GO
ALTER TABLE oys.ParentPart
ADD CONSTRAINT PK_ParentPart PRIMARY KEY NONCLUSTERED (ProgramGUID,ParentPartGUID);
ALTER TABLE oys.ParentPart
ADD CONSTRAINT FK_ParentPart_ParentPlate FOREIGN KEY (ProgramGUID)
  REFERENCES oys.ParentPlate(ProgramGUID) ON DELETE CASCADE;
CREATE UNIQUE CLUSTERED INDEX IX_AutoId ON oys.ParentPart(AutoId);
GO

USE SNInterDev;
CREATE TABLE oys.ChildPlate (
	AutoId BIGINT IDENTITY(1,1) NOT NULL,
	DBEntryDateTime DATETIME DEFAULT GETDATE(),
	ProgramGUID UNIQUEIDENTIFIER NOT NULL,
	ChildPlateGUID UNIQUEIDENTIFIER NOT NULL,
	PlateName VARCHAR(50),
	PlateNumber INT NOT NULL DEFAULT 1,
	MaterialMaster VARCHAR(50),
	Material VARCHAR(50),
	Thickness FLOAT,
	ChildNestTaskName VARCHAR(50),
	ChildNestProgramName VARCHAR(50),
	ChildNestRepeatID INT,
	Area FLOAT
);
GO
ALTER TABLE oys.ChildPlate
ADD CONSTRAINT PK_ChildPlate PRIMARY KEY NONCLUSTERED (ProgramGUID,ChildPlateGUID);
ALTER TABLE oys.ChildPlate
ADD CONSTRAINT FK_ChildPlate_Program FOREIGN KEY (ProgramGUID)
  REFERENCES oys.Program(ProgramGUID) ON DELETE CASCADE;
ALTER TABLE oys.ChildPlate
ADD CONSTRAINT UQ_ChildPlate_ChildPlateGUID UNIQUE (ChildPlateGUID);
CREATE UNIQUE CLUSTERED INDEX IX_AutoId ON oys.ChildPlate(AutoId);
GO

USE SNInterDev;
CREATE TABLE oys.ChildPart (
	AutoId BIGINT IDENTITY(1,1) NOT NULL,
	DBEntryDateTime DATETIME DEFAULT GETDATE(),
	ChildPlateGUID UNIQUEIDENTIFIER NOT NULL,
	ChildPartGUID UNIQUEIDENTIFIER NOT NULL,
	ParentPartGUID UNIQUEIDENTIFIER NOT NULL,
	SNPartName VARCHAR(100),
	SAPPartName VARCHAR(100),
	QtyProgram INT,
	Job VARCHAR(50),
	Shipment VARCHAR(50),
	QNNumber VARCHAR(50),
	TrueArea FLOAT,
	NestedArea FLOAT
);
GO
ALTER TABLE oys.ChildPart
ADD CONSTRAINT PK_ChildPart PRIMARY KEY NONCLUSTERED (ChildPlateGUID,ChildPartGUID);
ALTER TABLE oys.ChildPart
ADD CONSTRAINT FK_ChildPart_ChildPlate FOREIGN KEY (ChildPlateGUID)
  REFERENCES oys.ChildPlate(ChildPlateGUID) ON DELETE CASCADE;
CREATE UNIQUE CLUSTERED INDEX IX_AutoId ON oys.ChildPart(AutoId);
GO

USE SNInterDev;
CREATE TABLE oys.Remnant (
	AutoId BIGINT IDENTITY(1,1) NOT NULL,
	DBEntryDateTime DATETIME DEFAULT GETDATE(),
	ChildPlateGUID UNIQUEIDENTIFIER NOT NULL,
	RemnantGUID UNIQUEIDENTIFIER NOT NULL,
	RemnantName VARCHAR(50),
	Area FLOAT,
	IsRectangular BIT,
	RectWidth FLOAT,
	RectLength FLOAT
);
GO
ALTER TABLE oys.Remnant
ADD CONSTRAINT PK_Remnant PRIMARY KEY NONCLUSTERED (ChildPlateGUID,RemnantGUID);
ALTER TABLE oys.Remnant
ADD CONSTRAINT FK_Remnant_ChildPlate FOREIGN KEY (ChildPlateGUID)
  REFERENCES oys.ChildPlate(ChildPlateGUID) ON DELETE CASCADE;
CREATE UNIQUE CLUSTERED INDEX IX_AutoId ON oys.Remnant(AutoId);
GO

USE SNInterDev;
CREATE TABLE oys.Status (
	AutoId BIGINT IDENTITY(1,1) NOT NULL,
	DBEntryDateTime DATETIME DEFAULT GETDATE(),
	ProgramGUID UNIQUEIDENTIFIER NOT NULL,
	StatusGUID UNIQUEIDENTIFIER NOT NULL,
	SigmanestStatus VARCHAR(64),	-- 'Created', 'Released', or 'Deleted'
	SAPStatus VARCHAR(64),
	Source VARCHAR(64),	-- 'SAPPost', 'Split'
	UserName VARCHAR(64)
);
GO
ALTER TABLE oys.Status
ADD CONSTRAINT PK_Status PRIMARY KEY NONCLUSTERED (ProgramGUID,StatusGUID);
ALTER TABLE oys.Status
ADD CONSTRAINT FK_Status_Program FOREIGN KEY (ProgramGUID)
  REFERENCES oys.Program(ProgramGUID) ON DELETE CASCADE;
CREATE UNIQUE CLUSTERED INDEX IX_AutoId ON oys.Status(AutoId);
GO

USE SNInterDev;
GO


